// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "ocp"

// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "ocp.broker.saic.com"

// Base domain from which the cluster domain is a subdomain.
base_domain = "broker.saic.com"

datacenter_id = "OKR01-M01"

datastore = "OKR01-M01-VSAN"

folder = "OKR01 - VNS - Test VMs"

instance_count = "3"

ip_addresses = [("172.25.0.35"),("172.25.0.36"),("172.25.0.37")]

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.devcluster.openshift.com".

// vsphere_server = "COMP-APL-VCS01.broker.saic.com"
vsphere_server = "MGMT-APL-VCS01.broker.saic.com"

// User on the vSphere server.
vsphere_user = "SVC-VMW-vSphere-TF@broker.saic.com"

// Password of the user on the vSphere server.
vsphere_password = "ITaaSwins!!SAIC1811"

// Name of the vSphere cluster. The dev cluster is "devel".
// vsphere_cluster = "OKR01-C01-COMP01"
vsphere_cluster = "OKR01-M01-MGMT01"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "OKR01-M01"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "OKR01-M01-VSAN"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
vm_template = "TMPL-SVR-RHCOS01"

// The machine_cidr where IP addresses will be assigned for cluster nodes.
// Additionally, IPAM will assign IPs based on the network ID. 
machine_cidr = "172.25.0.0/16"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 3

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "https://fergusontrabucket.s3.amazonaws.com/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION

{"ignition":{"config":{"append":[{"source":"https://api-int.upi.broker.saic.com:22623/config/master","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJVzZtYm80c05GK3N3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEU1TURneU9EQXpNek15TkZvWApEVEk1TURneU5UQXpNek15TkZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE1VHNiWm8vZEk2dTUKSVlWemh4S21pNVg2L2tFWDVCdUNTMU9EUUx1SXlOQkFqY0VERjNzaVpmdlJKcEFOL2NYcG01cld6VjNqdTdkbQowd0lrbjM2WmdCUFliUjUyN0xFOHdQTnBaN21UTGNjUVlnNnhpdGZGN1ZvUVk2bUJodjF2Y0NLZEw5c0djY09jCkt3NHplaXhraVpXb2tjbkdsT1JhdUJGUHJHU2ZlUXA2c2FMNmJrRTlRN2JnVE96OXhqY29TNUZEK05DL3dVU2oKMUg0dDQxcHJWNnFZS1laMmI4WmY5REpzSDV3ODFiUG54ZDBzeTJiSUZKTHluK1AxRXArRjE2RlFhSEVRckpTWQpMR3dmcEVPVkRSOWRWdmtKT0oya29Dc2R4MGNWRVFBaGJnZTk3eno2VnJHbzVOSmhUaFpTR3AwQ1ExWWt5dkIzCmVkbDVWNmNOTndJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVNMUStoREJCcUdTTGJqMVRxREMrc0MyM2ZmVXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUpvMGZXM0lVRFVlQjh4MktTUk1tYlFNM2tuangyanlETmtHTmVkcWFsSFBOdXFXdFJic3pIbnUvdDk2Ck10azRWNTNqR2pSbWdDUWR5aGMwOGRXMENFbmFBNWFYWlpNMUthUFVNVndEeURZR3BPSVljNHh4Zk5wQzFvSlkKY2VpRzJhL09FS2FZUXpQYm5NK1djMUpaWlBvU3pqSnVFN2psSERWdmM2QnBjNzJ6ZTBKeDhKVTY1QTB1aXNsSgpNbVRqN25DYXYvRjE4Qkg1aTF0SG45cHZDY2JlbGZPaUFob2VZRXROcTJ1b0M5OWVUaS9OYm1pVnczYU9oYUFYClRmWXdmWmtTbGhhK3kvSXJwODA3Qk16VFJGNDBuTDBiWjFhZVNaTlNwZnJ4azZQSEtqMkJJckRaTVBzWDgxWkQKajl1cmI3cXR4ZGs5VHEvdTZEc05COTlzZ2NVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}

END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION

{"ignition":{"config":{"append":[{"source":"https://api-int.upi.broker.saic.com:22623/config/worker","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJVzZtYm80c05GK3N3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEU1TURneU9EQXpNek15TkZvWApEVEk1TURneU5UQXpNek15TkZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE1VHNiWm8vZEk2dTUKSVlWemh4S21pNVg2L2tFWDVCdUNTMU9EUUx1SXlOQkFqY0VERjNzaVpmdlJKcEFOL2NYcG01cld6VjNqdTdkbQowd0lrbjM2WmdCUFliUjUyN0xFOHdQTnBaN21UTGNjUVlnNnhpdGZGN1ZvUVk2bUJodjF2Y0NLZEw5c0djY09jCkt3NHplaXhraVpXb2tjbkdsT1JhdUJGUHJHU2ZlUXA2c2FMNmJrRTlRN2JnVE96OXhqY29TNUZEK05DL3dVU2oKMUg0dDQxcHJWNnFZS1laMmI4WmY5REpzSDV3ODFiUG54ZDBzeTJiSUZKTHluK1AxRXArRjE2RlFhSEVRckpTWQpMR3dmcEVPVkRSOWRWdmtKT0oya29Dc2R4MGNWRVFBaGJnZTk3eno2VnJHbzVOSmhUaFpTR3AwQ1ExWWt5dkIzCmVkbDVWNmNOTndJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVNMUStoREJCcUdTTGJqMVRxREMrc0MyM2ZmVXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUpvMGZXM0lVRFVlQjh4MktTUk1tYlFNM2tuangyanlETmtHTmVkcWFsSFBOdXFXdFJic3pIbnUvdDk2Ck10azRWNTNqR2pSbWdDUWR5aGMwOGRXMENFbmFBNWFYWlpNMUthUFVNVndEeURZR3BPSVljNHh4Zk5wQzFvSlkKY2VpRzJhL09FS2FZUXpQYm5NK1djMUpaWlBvU3pqSnVFN2psSERWdmM2QnBjNzJ6ZTBKeDhKVTY1QTB1aXNsSgpNbVRqN25DYXYvRjE4Qkg1aTF0SG45cHZDY2JlbGZPaUFob2VZRXROcTJ1b0M5OWVUaS9OYm1pVnczYU9oYUFYClRmWXdmWmtTbGhhK3kvSXJwODA3Qk16VFJGNDBuTDBiWjFhZVNaTlNwZnJ4azZQSEtqMkJJckRaTVBzWDgxWkQKajl1cmI3cXR4ZGs5VHEvdTZEc05COTlzZ2NVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}

END_OF_WORKER_IGNITION


// Set ipam and ipam_token if you want to use the IPAM server to reserve IP
// addresses for the VMs.

// Address or hostname of the IPAM server from which to reserve IP addresses for the cluster machines.
//ipam = "139.178.89.254"

// Token to use to authenticate with the IPAM server.
//ipam_token = "TOKEN_FOR_THE_IPAM_SERVER"


// Set bootstrap_ip, control_plane_ip, and compute_ip if you want to use static
// IPs reserved someone else, rather than the IPAM server.

// The IP address to assign to the bootstrap VM.
bootstrap_ip = "172.25.0.34"

// The IP addresses to assign to the control plane VMs. The length of this list
// must match the value of control_plane_count.
control_plane_ips = ["172.25.0.35","172.25.0.36","172.25.0.37"]

// The IP addresses to assign to the compute VMs. The length of this list must
// match the value of compute_count.
compute_ips = ["172.25.0.38","172.25.0.39","172.25.0.40"]
