// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "Red Hat-ocp"

// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "ocp.broker.saic.com"

// Base domain from which the cluster domain is a subdomain.
base_domain = "broker.saic.com"

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.devcluster.openshift.com".

// vsphere_server = "COMP-APL-VCS01.broker.saic.com"
# vsphere_server = "MGMT-APL-VCS01.broker.saic.com"

// USE IP because AWS doesn't have DNS set up
vsphere_server = "172.16.11.62"

// User on the vSphere server.
vsphere_user = "SVC-VMW-vSphere-TF@broker.saic.com"

// Password of the user on the vSphere server.
vsphere_password = "ITaaSwins!!SAIC1811"

// Name of the vSphere cluster. The dev cluster is "devel".
// vsphere_cluster = "OKR01-C01-COMP01"
vsphere_cluster = "OKR01-M01-MGMT01"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "OKR01-M01"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "OKR01-M01-MGMT01-VSAN"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
vm_template = "TMPL-SVR-RHCOS01"

// The machine_cidr where IP addresses will be assigned for cluster nodes.
// Additionally, IPAM will assign IPs based on the network ID. 
machine_cidr = "172.25.0.0/16"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 3

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "https://oakridge-ocp-bootstrap-ign.s3.amazonaws.com/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION

{"ignition":{"config":{"append":[{"source":"https://api-int.ocp.broker.saic.com:22623/config/master","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJTDBrQU1lblZsNWN3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURJd056RTFNRGd6TkZvWApEVE13TURJd05ERTFNRGd6TkZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzdmg3UUVrSjVGaHcKM09TYUZxZXhrcHVYMzcwcTZIUmZVdDFkNXdYUVhtVTlVSFFpdFFrc1R0SldSVTBYNFBLRVZxdUJ2L1dXbWZDYwpQcThzbGJTcURVamRsZ24ya0tJcWJjbkFvV3ZjaEZtcllFOXllbHg0UjI2dzJCRGRxd3ljSDNHcHBZSlFOWUw0CmFjb2tGSHVTTWo0WlN1R2VSRldISEg3dE1oOXJqMFl0dHZwanFlaFBWU09odEsvM3hUVzBhOHkrRDFDc0I4dWEKMVh0aWZCZUxyRjNnNXF5VW4vYlI3VnE0c2lpL1lVUzY0VkYyRVM2WVZhbFBkQy9MR0xTZFNEYXR2b0xkaW5aMQp5WHg4M0R1MDdsWVJKa0V3TVhNOTc2eHRYM2tyUEE4Q2IvakxEckwyRGJsaU9nd3piTk40YTJrTUE3Vm5DYkg0ClB1djNkR25rSlFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVhUc3UrZ0R5VHE1VExOY2NMQTkrZXprdDVRQXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUoxS3A5VURGNlczU01vK3dyS3FPTGRtZ2didVhXK3RCS0w3aExPWTRaWjhtNTJZNFdyQlU0V1FGYndHCkhNQTdITHpORSs0b3h0SFg2eFA3eUFCb2hUWXFXYVVtNWFVSXluWkNrQi94a2ZXeS9IemdpZ21xRFR6NHZkZFUKNHpibVBLU2pSd0Y2Wm5OWUplQVVNUEh2cEJZaVNicjVDU0s5YmhJS3d3ZFI1VFpQT2IrVlFoMEJUNHNSVDNCNApDdTVwTVE3cEpkaFV3Vjg2Tkl6K2YyQzRRWkIyTlA4OU9STlR4SWFuemZaSG1kYkF5RUlHN0ExYjZtV016RmplClNGN1RJaVY2bysxUjR2NTRPbEwzdlBxZzNPNlRkRURUcnRTRVl3Yi90NHQ3azlnWVd0ckNOWUhDZ3RpeHRhVkgKR1JoZDZaN0REU3pFSFBRMW9XRlZrdExSU1lVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION

{"ignition":{"config":{"append":[{"source":"https://api-int.ocp.broker.saic.com:22623/config/worker","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJTDBrQU1lblZsNWN3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURJd056RTFNRGd6TkZvWApEVE13TURJd05ERTFNRGd6TkZvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzdmg3UUVrSjVGaHcKM09TYUZxZXhrcHVYMzcwcTZIUmZVdDFkNXdYUVhtVTlVSFFpdFFrc1R0SldSVTBYNFBLRVZxdUJ2L1dXbWZDYwpQcThzbGJTcURVamRsZ24ya0tJcWJjbkFvV3ZjaEZtcllFOXllbHg0UjI2dzJCRGRxd3ljSDNHcHBZSlFOWUw0CmFjb2tGSHVTTWo0WlN1R2VSRldISEg3dE1oOXJqMFl0dHZwanFlaFBWU09odEsvM3hUVzBhOHkrRDFDc0I4dWEKMVh0aWZCZUxyRjNnNXF5VW4vYlI3VnE0c2lpL1lVUzY0VkYyRVM2WVZhbFBkQy9MR0xTZFNEYXR2b0xkaW5aMQp5WHg4M0R1MDdsWVJKa0V3TVhNOTc2eHRYM2tyUEE4Q2IvakxEckwyRGJsaU9nd3piTk40YTJrTUE3Vm5DYkg0ClB1djNkR25rSlFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVhUc3UrZ0R5VHE1VExOY2NMQTkrZXprdDVRQXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUoxS3A5VURGNlczU01vK3dyS3FPTGRtZ2didVhXK3RCS0w3aExPWTRaWjhtNTJZNFdyQlU0V1FGYndHCkhNQTdITHpORSs0b3h0SFg2eFA3eUFCb2hUWXFXYVVtNWFVSXluWkNrQi94a2ZXeS9IemdpZ21xRFR6NHZkZFUKNHpibVBLU2pSd0Y2Wm5OWUplQVVNUEh2cEJZaVNicjVDU0s5YmhJS3d3ZFI1VFpQT2IrVlFoMEJUNHNSVDNCNApDdTVwTVE3cEpkaFV3Vjg2Tkl6K2YyQzRRWkIyTlA4OU9STlR4SWFuemZaSG1kYkF5RUlHN0ExYjZtV016RmplClNGN1RJaVY2bysxUjR2NTRPbEwzdlBxZzNPNlRkRURUcnRTRVl3Yi90NHQ3azlnWVd0ckNOWUhDZ3RpeHRhVkgKR1JoZDZaN0REU3pFSFBRMW9XRlZrdExSU1lVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_WORKER_IGNITION

// Set ipam and ipam_token if you want to use the IPAM server to reserve IP
// addresses for the VMs.

// Address or hostname of the IPAM server from which to reserve IP addresses for the cluster machines.
//ipam = "139.178.89.254"

// Token to use to authenticate with the IPAM server.
//ipam_token = "TOKEN_FOR_THE_IPAM_SERVER"


// Set bootstrap_ip, control_plane_ip, and compute_ip if you want to use static
// IPs reserved someone else, rather than the IPAM server.

// The IP address to assign to the bootstrap VM.
bootstrap_ip = "172.25.0.34"

// The IP addresses to assign to the control plane VMs. The length of this list
// must match the value of control_plane_count.
control_plane_ips = ["172.25.0.35","172.25.0.36","172.25.0.37"]

// The IP addresses to assign to the compute VMs. The length of this list must
// match the value of compute_count.
compute_ips = ["172.25.0.38","172.25.0.39","172.25.0.40"]

